export {
  BookOpenText as BookOpenTextIcon,
  GraduationCap as GraduationCapIcon,
  LibraryBig as LibraryIcon,
  CircleGauge as PerformanceIcon,
  ShieldCheck as SecurityIcon,
  MonitorSmartphone as EaseToUseIcon,
  Folder as ChatWithFolderIcon,
  Brain as BrainIcon,
  NotebookPen as NotebookPenIcon,
  MessageCircleMore as ChatIcon,
  LineChart as AnalysesIcon,
  Star as StarIcon,
  PenTool as SummarizeIcon,
} from 'lucide-react';
